language: python
os: linux
dist: xenial
cache: pip
python:
  - 2.7
  - 3.6
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest pytest-cov
script:
  - cd tests
  - pytest --cov=../waybackpy
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then python -m codecov; fi
